server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://47.75.50.105:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: cqssc1998
    name: root