server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/newCqssc?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: utf-8
      enabled: true

logging:
  level:
    com.hncp.cqssc.mapper : debu